ephec_main_homepage:
    path:     /main
    defaults: { _controller: EPHECMainBundle:Default:index }
ephec_main_android:
    path:     /android/{test}/{name}
    defaults: { _controller: EPHECMainBundle:Default:loginAndroid }
