ephec_main_homepage:
    path:     /
    defaults: { _controller: EPHECMainBundle:Default:index }

ephec_android_login:
    path: /android/login
    defaults: { _controller: EPHECMainBundle:Default:androidlogin}

ephec_android_memolist:
    path: /android/memolist
    defaults: { _controller: EPHECMainBundle:Default:androidmemolist}

ephec_android_memolist:
    path: /android/memolist
    defaults: { _controller: EPHECMainBundle:Default:androidmemolist}

ephec_android_getuser:
    path: /android/getuser
    defaults: { _controller: EPHECMainBundle:Default:androidgetuser}

ephec_android_edituser:
    path: /android/edituser
    defaults: { _controller: EPHECMainBundle:Default:androidedituser}