ephec_main_homepage:
    path:     /
    defaults: { _controller: EPHECMainBundle:Default:index }

ephec_android_login:
    path: /android/login
    defaults: { _controller: EPHECMainBundle:Default:androidlogin}

ephec_android_register:
    path: /android/register
    defaults: { _controller: EPHECMainBundle:Default:androidregister}