ephec_note:
    resource: "@EPHECNoteBundle/Resources/config/routing.yml"
    prefix:   /

ephec_main:
    resource: "@EPHECMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
