<?php

namespace EPHEC\Bundle\NoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends EntityRepository
{
    public function findAlarmByGroups($groups)
    {
        return $this->createQueryBuilder('alarm')
            ->getQuery()
            ->getResult();
    }
}