ephec_note_homepage:
    path:     /
    defaults: { _controller: EPHECNoteBundle:Default:index }
ephec_note_addMemo:
    path:     /add
    defaults: { _controller: EPHECNoteBundle:Default:addMemo }
ephec_note_editMemo:
    path:     /edit/{idMemo}
    defaults: { _controller: EPHECNoteBundle:Default:editMemo }
