ephec_note_homepage:
    path:     /
    defaults: { _controller: EPHECNoteBundle:Default:index }
ephec_note_addMemo:
    path:     /add
    defaults: { _controller: EPHECNoteBundle:Default:addMemo }
ephec_note_editMemo:
    path:     /edit/{idMemo}
    defaults: { _controller: EPHECNoteBundle:Default:editMemo }
ephec_note_archive:
    path:     /archive/{idMemo}
    defaults: { _controller: EPHECNoteBundle:Default:archiveMemo }
ephec_note_archived:
    path:     /archived/{val}
    defaults: { _controller: EPHECNoteBundle:Default:index }
ephec_note_archivedMemo:
    path:     /archivedMemo
    defaults: { _controller: EPHECNoteBundle:Default:archiveList }
ephec_note_archivedMemoArchive:
    path:     /archivedMemo/archive/{idMemo}
    defaults: { _controller: EPHECNoteBundle:Default:archiveListArchive }
ephec_note_archivedMemoActive:
    path:     /archivedMemo/active/{idMemo}
    defaults: { _controller: EPHECNoteBundle:Default:archiveListActive }